<textarea name="textarea">;<html>;</textarea>;
<textarea name="textarea">;&html& </textarea>;
<textarea name="textarea">;&/textarea& </textarea>;







e...<?php echo $this->vars->title;





/*	$this->form::add(
		'text(username): default_value=欢迎光临', 
		'password(password): default_value=欢迎光临', 
		'hidden(username): default_value=欢迎光临|method=342|', 
		'select(shirt): options=k=>v,k=>v||', 
	)::show('method=get,');
*/